version = 1

exclude_patterns = [
    "**/build/**",
    "**/node_modules/**"
]

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

    [analyzers.meta]
    module_system = "es-modules"
    environment = [
        "nodejs",
    ]
    dialect = "typescript"
    skip_doc_coverage = ["class-expression", "method-definition", "class-declaration", "function-declaration"]

[[transformers]]
name = "prettier"
enabled = true
