name: Deprecate - NPM Version
on:
  workflow_dispatch:
    inputs:
      package:
        description: "package"
        required: true
        type: string
      version:
        description: "npm version range"
        required: true
        type: string
      message:
        description: "deprecate message"
        default: "Version no longer supported. Upgrade to @latest"
        required: true
        type: string

jobs:
  deprecate:
    if: github.actor == 'samarmeena'
    runs-on: ubuntu-latest
    steps:
      - name: check out code ðŸ›Ž
        uses: actions/checkout@v3

      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Deprecate version
        run: npm deprecate ${{ github.event.inputs.package }}@"${{ github.event.inputs.version }}" "${{ github.event.inputs.message }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
