name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    paths-ignore:
      - "docs/docs/**"
    branches:
      - main

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: check out code ðŸ›Ž
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: check out code ðŸ›Ž
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: "Changelog: Install Dependencies"
        run: npm ci
        working-directory: ./packages/changelog

      - name: "Importer: Install Dependencies"
        run: npm ci
        working-directory: ./packages/importer

      - name: "Music: Install Dependencies"
        run: npm ci
        working-directory: ./packages/music

      - name: "Utilities: Install Dependencies"
        run: npm ci
        working-directory: ./packages/utilities

      - name: Run TypeScript compiler
        run: npm run type-check

      - name: "Changelog: Run TypeScript compiler"
        run: npm run type-check
        working-directory: ./packages/changelog

      - name: "Importer: Run TypeScript compiler"
        run: npm run type-check
        working-directory: ./packages/importer

      - name: "Music: Run TypeScript compiler"
        run: npm run type-check
        working-directory: ./packages/music

      - name: "Utilities: Run TypeScript compiler"
        run: npm run type-check
        working-directory: ./packages/utilities

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: check out code ðŸ›Ž
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run prettier
        run: npm run format-check

  jest:
    name: Jest Tests
    runs-on: ubuntu-latest
    steps:
      - name: check out code ðŸ›Ž
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test
