name: Publish - Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies for docs
        run: npm install
        working-directory: ./docs

      - name: Build docs
        run: npm run build
        working-directory: ./docs

      - name: Add CNAME
        run: echo discordx.js.org > CNAME
        working-directory: ./docs/build

      - name: Publish git branch
        run: |
          git init -b gh-pages
          git config user.email ${{ secrets.GIT_EMAIL }}
          git config user.name ${{ secrets.GIT_NAME }}
          git add -A
          git commit -m 'docs'
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push --force --set-upstream origin gh-pages
        working-directory: ./docs/build
