name: Publish - Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install root dependencies
        run: npm ci

      - name: Install doc dependencies
        run: npm ci
        working-directory: ./docs

      - name: "Utilities: Install Dependencies"
        run: npm ci
        working-directory: ./packages/utilities

      - name: "Music: Install Dependencies"
        run: npm ci
        working-directory: ./packages/music

      - name: Build docs
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
        working-directory: ./docs

      - name: Add CNAME
        run: echo discord-ts.js.org > CNAME
        working-directory: ./docs/build

      - name: Publish git branch
        run: |
          git init -b gh-pages
          git config user.email ${{ secrets.GIT_EMAIL }}
          git config user.name ${{ secrets.GIT_NAME }}
          git add -A
          git commit -m 'docs'
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push --force --set-upstream origin gh-pages
        working-directory: ./docs/build
