name: Publish - Documentation
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: check out code ðŸ›Ž
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install root dependencies
        run: npm ci

      - name: Install doc dependencies
        run: npm ci
        working-directory: ./docs

      - name: Build docs
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
        working-directory: ./docs

      - name: Add CNAME
        run: echo discord-ts.js.org > CNAME
        working-directory: ./docs/build

      - name: Publish git branch
        run: |
          git init -b gh-pages
          git config user.email ${{ secrets.GIT_EMAIL }}
          git config user.name ${{ secrets.GIT_NAME }}
          git add -A
          git commit -m 'docs'
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push --force --set-upstream origin gh-pages
        working-directory: ./docs/build
